name: CI build

on:
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_wrapper:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

  jlink:
    name: Create JRE
    runs-on: windows-latest

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 24
          distribution: 'temurin'

      - name: Package JDK
        run: jlink --add-modules java.base --output jre --strip-debug --no-man-pages --no-header-files

      - name: Upload JDK package
        uses: actions/upload-artifact@v4
        with:
          name: jre
          path: jre

  build:
    name: Build Jar
    needs: [check_wrapper, jlink]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 24
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Download JRE
        uses: actions/download-artifact@v4
        with:
          name: jre
          path: jre

      - name: Build Jar
        run: ./gradlew :fatjar

      - name: Get tag name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build Package
        run: |
          mkdir ./output
          mv ./build/libs/UsbMonitorHandler-*.jar ./output/UsbMonitorHandler.jar
          mv ./jre ./output/jre
          cp ./scripts/Run.bat ./output/Run.bat
          cd ./output
          zip -r UsbMonitorHandler-${TAG_NAME}.zip ./
          mv UsbMonitorHandler-${TAG_NAME}.zip ../
          cd ..

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: UsbMonitorHandler-${{ env.TAG_NAME }}.zip
          draft: true
